{% set name = "harfile" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/harfile-{{ version }}.tar.gz
  sha256: 23be8037e1296bb4787a15543a37835ed91f408c8296988f9ba022a44accad9e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - harfile
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/schemathesis/harfile
  summary: Writer for HTTP Archive (HAR) files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
