{% set name = "harfile" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/harfile-{{ version }}.tar.gz
  sha256: 8998fa4410ad17d7b5671bab36ea058adde835bbb27f6a3da4b423019da584da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - harfile
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/schemathesis/harfile
  summary: Writer for HTTP Archive (HAR) files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
